---
# tasks file for vm_provision, создание snapshot
- name: Создание snapshot {{ snapshot_name }}
  shell: "virsh snapshot-create-as --domain {{ vm_name }} --name {{ snapshot_name }} --description '{{ snapshot_description }}'"
  register: snapshot_create_status
  ignore_errors: true
